const API='https://api.binance.com/api/v3';
let chart=null,currentResearch=null,scannerRows=[];
const $=id=>document.getElementById(id);
const money=n=>'$ '+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:8});
const fmt=n=>Number(n||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const attr=s=>esc(s).replace(/javascript:/gi,'');
async function getJSON(url,opts={}){const r=await fetch(url,opts);if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function authHeaders(){const token=window.clyptoGetToken?await window.clyptoGetToken():null;return token?{Authorization:`Bearer ${token}`}:{}}
function sma(a,p){return a.length<p?null:a.slice(-p).reduce((x,y)=>x+y,0)/p}
function ema(a,p){if(a.length<p)return null;const k=2/(p+1);let e=sma(a.slice(0,p),p);for(let i=p;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,p=14){if(a.length<=p)return 50;let g=0,l=0;for(let i=1;i<=p;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;for(let i=p+1;i<a.length;i++){const d=a[i]-a[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p}return l===0?100:100-100/(1+g/l)}
function vol(a){if(a.length<2)return 0;const r=a.slice(1).map((x,i)=>x/a[i]-1),m=r.reduce((x,y)=>x+y,0)/r.length;return Math.sqrt(r.reduce((x,y)=>x+(y-m)**2,0)/r.length)*100}
function setLoading(el,text='Carregando...'){if(el)el.innerHTML=`<div class="loading"><span></span><span></span><span></span> ${esc(text)}</div>`}
function openModal(html){$('modalBody').innerHTML=html;$('modal').classList.add('open')}
function closeModal(){$('modal').classList.remove('open')}
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='alertsView')renderAlertsFull();if(id==='historyView')loadHistory($('historyAssetFilter').value);if(id==='newsView')renderFullNews()}
function technical(c,v){const s20=sma(c,20),s50=sma(c,50),rr=rsi(c),mac=ema(c,12)-ema(c,26),va=sma(v,20),last=c.at(-1),score=(last>s20?1:0)+(last>s50?1:0)+(s20>s50?1:0)+(rr>50&&rr<70?1:0)+(mac>0?1:0)+(v.at(-1)>va?1:0);return{s20,s50,rr,mac,vol:vol(c.slice(-50)),last,score,label:score>=4?'Tendência positiva':score<=2?'Tendência negativa':'Neutra'}}
async function load(){const symbol=$('symbol').value,interval=$('interval').value;$('status').textContent='Consultando mercado...';try{const[t,k]=await Promise.all([getJSON(`${API}/ticker/24hr?symbol=${symbol}`),getJSON(`${API}/klines?symbol=${symbol}&interval=${interval}&limit=200`)]);const c=k.map(x=>+x[4]),v=k.map(x=>+x[5]),a=technical(c,v);$('price').textContent=money(t.lastPrice);$('change').textContent=fmt(t.priceChangePercent)+'%';$('change').className=Number(t.priceChangePercent)>=0?'up':'down';$('priceTime').textContent='Binance · atualizado agora';$('rsi').textContent=a.rr.toFixed(1);$('sma20').textContent=money(a.s20);$('sma50').textContent=money(a.s50);$('macd').textContent=money(a.mac);$('volatility').textContent=fmt(a.vol)+'%';$('trend').textContent=a.label;const cls=a.score>=4?'bull':a.score<=2?'bear':'neutral';$('signal').className='signal '+cls;$('signal').textContent=a.label;$('report').innerHTML=`<p><b>Leitura técnica:</b> ${esc(a.label)} (${a.score}/6 critérios).</p><p>RSI ${a.rr.toFixed(1)} · MACD ${money(a.mac)} · volatilidade ${fmt(a.vol)}%.</p><p>Volume recente ${v.at(-1)>sma(v,20)?'acima':'abaixo'} da média de 20 períodos.</p>`;const labels=k.map(x=>new Date(x[0]).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}));if(chart)chart.destroy();chart=new Chart($('priceChart'),{type:'line',data:{labels,datasets:[{label:symbol,data:c,borderWidth:2,pointRadius:0,tension:.2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{maxTicksLimit:8}},y:{ticks:{callback:x=>'$'+Number(x).toLocaleString()}}}}});$('status').textContent='Mercado atualizado';await research(true)}catch(e){$('status').textContent='Falha ao carregar dados';console.error(e)}}
async function research(silent=false){const symbol=$('symbol').value;if(!silent)$('status').textContent='🧠 Analisando notícias + sentimento + IA...';$('researchBtn').disabled=true;setLoading($('news'),'Buscando notícias');setLoading($('aiReport'),'Gerando relatório');try{const data=await getJSON(`/api/research?symbol=${encodeURIComponent(symbol)}`);currentResearch=data;renderResearch(data);loadHistory(symbol);$('updated').textContent='Atualizado '+new Date(data.updatedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});$('status').textContent='Pesquisa concluída · '+(data.news?.length||0)+' notícias'}catch(e){$('status').textContent='Pesquisa indisponível';$('news').innerHTML='<div class="empty error">Não foi possível carregar as notícias. Tente novamente.</div>';console.error(e)}finally{$('researchBtn').disabled=false}}
function renderResearch(d){const s=d.sentiment?.score||0,label=d.sentiment?.label||'neutral',score=d.score?.score??'—';$('sentimentValue').textContent=(label==='bull'?'🟢 ':label==='bear'?'🔴 ':'🟡 ')+Math.round(s);$('newsCount').textContent=(d.news?.length||0)+' notícias';$('scoreValue').textContent=score+'/100';const risk=d.technical?.volatility>5?'Alto':d.technical?.volatility>2.5?'Médio':'Baixo';$('riskValue').textContent=risk;$('riskValue').className='risk-'+risk.toLowerCase();$('sentiment').className='sentiment '+label;$('sentiment').innerHTML=`<b>${label==='bull'?'Sentimento positivo':label==='bear'?'Sentimento negativo':'Sentimento neutro'}</b><strong>${Math.round(s)}/100</strong>`;const positive=d.news?.filter(n=>n.sentiment?.label==='bull').length||0,negative=d.news?.filter(n=>n.sentiment?.label==='bear').length||0,neutral=(d.news?.length||0)-positive-negative,total=d.news?.length||1;$('positiveBar').textContent=Math.round(positive/total*100)+'%';$('neutralBar').textContent=Math.round(neutral/total*100)+'%';$('negativeBar').textContent=Math.round(negative/total*100)+'%';renderBreakdown(d);renderNews(d.news||[]);const ai=d.ai||{};$('aiReport').innerHTML=`<p class="ai-summary">${esc(ai.summary||'Sem resumo disponível.')}</p><div class="ai-cols"><div><b>⚠️ Riscos</b><ul>${(ai.risks||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>Não informado</li>'}</ul></div><div><b>👀 Pontos de atenção</b><ul>${(ai.watch||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>Não informado</li>'}</ul></div></div>`}
function renderBreakdown(d){const b=d.score?.breakdown||[];$('scoreBreakdown').innerHTML=b.map(x=>`<button class="factor" data-factor="${x.key}"><span><b>${esc(x.label)}</b><small>${x.weight}% do score</small></span><div class="factor-bar"><i style="width:${x.value}%"></i></div><strong>+${x.contribution}</strong></button>`).join('')+`<div class="factor-note">${esc(d.score?.formula||'Metodologia do score')}</div>`;document.querySelectorAll('.factor').forEach(el=>el.onclick=()=>showFactor(el.dataset.factor,d))}
function showFactor(key,d){const x=(d.score?.breakdown||[]).find(v=>v.key===key);const t=d.technical||{};let details=[];if(key==='technical')details=['Preço vs SMA20: '+(t.price>t.sma20?'acima':'abaixo'),'Preço vs SMA50: '+(t.price>t.sma50?'acima':'abaixo'),'RSI: '+fmt(t.rsi),'MACD: '+money(t.macd)];if(key==='sentiment')details=['Sentimento agregado: '+(d.sentiment?.score??0)+'/100','Classificação: '+(d.sentiment?.label||'neutral')];if(key==='news')details=['Notícias analisadas: '+(d.news?.length||0),'Média de sentimento das notícias usada no cálculo.'];if(key==='volume')details=['Volume 24h: '+Number(t.volume24h||0).toLocaleString('en-US'),'Volume recente: '+(t.volumeAboveAverage?'acima':'abaixo')+' da média'];if(key==='momentum')details=['MACD: '+money(t.macd),'Momentum '+(t.macd>=0?'positivo':'negativo')];if(key==='stability')details=['Volatilidade: '+fmt(t.volatility)+'%','Índice de estabilidade ajustado à volatilidade.'];openModal(`<h3>${esc(x?.label||key)}</h3><p>Contribuição: <b>+${x?.contribution||0}</b> · peso ${x?.weight||0}%.</p><ul>${details.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`)}
function renderNews(items){$('news').innerHTML=items.length?items.slice(0,8).map((n,i)=>newsCard(n,i)).join(''):'<div class="empty">Nenhuma notícia encontrada.</div>';document.querySelectorAll('[data-news]').forEach(el=>el.onclick=()=>showNews(items[Number(el.dataset.news)]))}
function newsCard(n,i){const l=n.sentiment?.label||'neutral';return `<article class="news-item" data-news="${i}"><div class="news-top"><span class="dot ${l}"></span><small>${esc(n.source||'Fonte')} · ${new Date(n.publishedAt).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}</small></div><h3>${esc(n.title)}</h3><span class="tag ${l}">${l==='bull'?'Positiva':l==='bear'?'Negativa':'Neutra'}</span></article>`}
function showNews(n){openModal(`<span class="eyebrow">NOTÍCIA</span><h2>${esc(n.title)}</h2><p><b>Fonte:</b> ${esc(n.source||'Fonte externa')}</p><p><b>Publicada:</b> ${new Date(n.publishedAt).toLocaleString('pt-BR')}</p><p><b>Sentimento:</b> ${esc(n.sentiment?.label||'neutral')}</p><a class="primary link-btn" href="${attr(n.url)}" target="_blank" rel="noopener">Ler notícia original ↗</a>`)}
async function loadHistory(symbol){try{const d=await getJSON(`/api/research/history?symbol=${symbol}&limit=30`);renderHistory(d.history||[])}catch(e){$('historyPreview').innerHTML='<div class="empty">Histórico ainda indisponível.</div>';$('historyFull').innerHTML='<div class="empty">Histórico ainda indisponível.</div>'}}
function renderHistory(items){const html=items.length?items.map((h,i)=>`<button class="history-row" data-history="${i}"><span>${new Date(h.snapshotAt||h.updatedAt).toLocaleString('pt-BR')}</span><b>${h.score?.score??'—'}</b><span>${money(h.technical?.price)}</span><span class="tag ${h.sentiment?.label||'neutral'}">${h.sentiment?.label||'neutral'}</span></button>`).join(''):'<div class="empty">Nenhuma pesquisa histórica registrada.</div>';if($('historyPreview'))$('historyPreview').innerHTML=items.slice(0,5).length?items.slice(0,5).map((h,i)=>`<button class="history-row" data-history="${i}"><span>${new Date(h.snapshotAt||h.updatedAt).toLocaleString('pt-BR')}</span><b>${h.score?.score??'—'}</b><span>${money(h.technical?.price)}</span></button>`).join(''):'<div class="empty">Nenhuma pesquisa histórica.</div>';$('historyFull').innerHTML=html;document.querySelectorAll('[data-history]').forEach(el=>el.onclick=()=>showHistory(items[Number(el.dataset.history)]))}
function showHistory(h){openModal(`<span class="eyebrow">SNAPSHOT HISTÓRICO</span><h2>${esc(h.asset||h.symbol)}</h2><div class="history-detail"><b>Score ${h.score?.score??'—'}/100</b><span>Preço ${money(h.technical?.price)}</span><span>Sentimento ${h.sentiment?.score??0}/100</span><span>${new Date(h.snapshotAt||h.updatedAt).toLocaleString('pt-BR')}</span></div><h3>Fatores</h3><ul>${(h.score?.breakdown||[]).map(x=>`<li>${esc(x.label)}: ${x.value}/100 · contribuição +${x.contribution}</li>`).join('')}</ul><button class="primary" onclick="window.compareSnapshot('${h.id||''}')">Comparar com pesquisa atual</button></div>`)}
window.compareSnapshot=id=>{if(!currentResearch)return;const h=(currentResearch._history||[]).find(x=>x.id===id);openModal('<h3>Comparação</h3><p>Pesquisa histórica selecionada. Para uma comparação completa, carregue o ativo novamente e compare os snapshots pelo score, preço e sentimento.</p>')};
async function scan(){const symbols=['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT','ADAUSDT','DOGEUSDT','AVAXUSDT','LINKUSDT','DOTUSDT'];$('status').textContent='Executando scanner...';setLoading($('scannerTable'),'Analisando 10 ativos');scannerRows=[];for(const symbol of symbols){try{const[t,k,r]=await Promise.all([getJSON(`${API}/ticker/24hr?symbol=${symbol}`),getJSON(`${API}/klines?symbol=${symbol}&interval=1d&limit=100`),getJSON(`/api/research?symbol=${symbol}`)]);const c=k.map(x=>+x[4]),v=k.map(x=>+x[5]),a=technical(c,v);scannerRows.push({symbol,price:+t.lastPrice,change:+t.priceChangePercent,rsi:a.rr,trend:a.label,score:r.score?.score??Math.round(a.score/6*100),sentiment:r.sentiment?.label||'neutral'})}catch(e){console.warn(symbol,e)}}renderScanner();$('status').textContent='Scanner concluído · '+scannerRows.length+' ativos'}
function renderScanner(){let rows=[...scannerRows];const sf=$('scoreFilter').value,tf=$('sentimentFilter').value,sort=$('sortFilter').value;if(sf==='high')rows=rows.filter(x=>x.score>=80);if(sf==='mid')rows=rows.filter(x=>x.score>=60&&x.score<80);if(sf==='low')rows=rows.filter(x=>x.score<60);if(tf!=='all')rows=rows.filter(x=>x.sentiment===tf);rows.sort((a,b)=>sort==='change'?b.change-a.change:sort==='price'?b.price-a.price:b.score-a.score);$('scannerTable').innerHTML=`<table><thead><tr><th>Ativo</th><th>Score</th><th>Sentimento</th><th>Preço</th><th>24h</th><th>RSI</th></tr></thead><tbody>${rows.map(r=>`<tr class="clickable" data-symbol="${r.symbol}"><td><b>${r.symbol.replace('USDT','')}</b></td><td><span class="score-pill">${r.score}</span></td><td><span class="tag ${r.sentiment}">${r.sentiment}</span></td><td>${money(r.price)}</td><td class="${r.change>=0?'up':'down'}">${fmt(r.change)}%</td><td>${fmt(r.rsi)}</td></tr>`).join('')}</tbody></table>`;document.querySelectorAll('[data-symbol]').forEach(el=>el.onclick=()=>selectAsset(el.dataset.symbol))}
function selectAsset(symbol){$('symbol').value=symbol;switchView('dashboard');load()}
async function createAlert(){const symbol=$('symbol').value,price=Number($('alertPrice').value),direction=$('alertDirection').value;if(!price)return alert('Informe o preço-alvo.');try{const h=await authHeaders();h['Content-Type']='application/json';await getJSON('/api/alerts',{method:'POST',headers:h,body:JSON.stringify({symbol,price,direction})});$('alertPrice').value='';await loadAlerts();openModal('<h3>🔔 Alerta criado</h3><p>O Clypto vai monitorar a condição configurada.</p>')}catch(e){alert('Não foi possível criar o alerta. Configure Firebase Authentication.')}}
async function loadAlerts(){try{const h=await authHeaders(),d=await getJSON('/api/alerts',{headers:h});renderAlerts(d.alerts||[])}catch(e){renderAlerts([])}}
function renderAlerts(items){const html=items.length?items.map(a=>`<button class="alert-row" data-alert="${a.id}"><span><b>${esc(a.symbol.replace('USDT',''))}</b> ${a.direction==='above'?'≥':'≤'} ${money(a.price)}</span><small>🟢 ativo</small></button>`).join(''):'<div class="empty">Nenhum alerta ativo.</div>';if($('alerts'))$('alerts').innerHTML=html;if($('alertsFull'))$('alertsFull').innerHTML=html}
function renderAlertsFull(){loadAlerts()}
function renderFullNews(){if(!currentResearch){$('newsFull').innerHTML='<div class="empty">Pesquise um ativo primeiro.</div>';return}let items=currentResearch.news||[];const f=$('newsSentimentFilter').value;if(f!=='all')items=items.filter(n=>n.sentiment?.label===f);$('newsFull').innerHTML=items.map((n,i)=>newsCard(n,i)).join('')||'<div class="empty">Nenhuma notícia para este filtro.</div>';document.querySelectorAll('#newsFull [data-news]').forEach(el=>el.onclick=()=>showNews(items[Number(el.dataset.news)]))}
$('analyzeBtn').onclick=load;$('refreshBtn').onclick=load;$('researchBtn').onclick=()=>research(false);$('scanBtn').onclick=scan;$('createAlertBtn').onclick=createAlert;$('viewNews').onclick=()=>switchView('newsView');$('viewHistory').onclick=()=>switchView('historyView');$('sentimentDetails').onclick=()=>openModal(`<h3>Sentimento</h3><p>O Clypto agrega o sentimento classificado nas notícias coletadas. A classificação é indicativa e pode conter limitações de cobertura e idioma.</p>`);$('modalClose').onclick=closeModal;$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('scoreFilter').onchange=renderScanner;$('sentimentFilter').onchange=renderScanner;$('sortFilter').onchange=renderScanner;$('newsAssetFilter').onchange=()=>{selectAsset($('newsAssetFilter').value);switchView('newsView')};$('newsSentimentFilter').onchange=renderFullNews;$('historyAssetFilter').onchange=e=>loadHistory(e.target.value);
loadAlerts();load();