const { onRequest, onSchedule } = require('firebase-functions/v2/https');
const { setGlobalOptions } = require('firebase-functions/v2');
const { defineSecret } = require('firebase-functions/params');
const admin = require('firebase-admin');
admin.initializeApp();
setGlobalOptions({ region: 'southamerica-east1', maxInstances: 5 });
const db = admin.firestore();
const GEMINI_API_KEY = defineSecret('GEMINI_API_KEY');
const GEMINI_MODEL = process.env.GEMINI_MODEL || 'gemini-2.5-flash';
const BINANCE = 'https://api.binance.com/api/v3';
const SYMBOLS=['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT','ADAUSDT','DOGEUSDT','AVAXUSDT','LINKUSDT','DOTUSDT'];
const POSITIVE=['surge','rally','gain','gains','bullish','breakout','growth','adoption','approval','approved','inflow','record','high','rise','rises','positive','support','partnership','upgrade','increasing'];
const NEGATIVE=['crash','fall','falls','drop','drops','bearish','hack','hacked','exploit','lawsuit','ban','banned','outflow','low','negative','liquidation','liquidations','risk','risks','fraud','scam','regulation','regulatory'];
function sentiment(text=''){const words=text.toLowerCase().replace(/[^a-z0-9\s-]/g,' ').split(/\s+/);let p=0,n=0;for(const w of words){if(POSITIVE.includes(w))p++;if(NEGATIVE.includes(w))n++}const score=Math.max(-100,Math.min(100,(p-n)*12));return{score,label:score>15?'bull':score<-15?'bear':'neutral'}}
function assetName(symbol){return symbol.replace('USDT','')}
async function getJson(url,options={}){const r=await fetch(url,options);if(!r.ok)throw new Error(`HTTP ${r.status} ${url}`);return r.json()}
function average(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function rsi(closes,p=14){if(closes.length<=p)return 50;let g=0,l=0;for(let i=1;i<=p;i++){const d=closes[i]-closes[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;for(let i=p+1;i<closes.length;i++){const d=closes[i]-closes[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p}return l===0?100:100-100/(1+g/l)}
function ema(a,p){if(a.length<p)return average(a);const k=2/(p+1);let e=average(a.slice(0,p));for(let i=p;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function volatility(a){if(a.length<2)return 0;const r=a.slice(1).map((x,i)=>x/a[i]-1),m=average(r);return Math.sqrt(average(r.map(x=>(x-m)**2)))*100}
async function fetchNews(symbol){const asset=assetName(symbol);const query=encodeURIComponent(`(${asset} OR cryptocurrency OR crypto) AND (market OR price OR regulation OR adoption)`);const data=await getJson(`https://api.gdeltproject.org/api/v2/doc/doc?query=${query}&mode=artlist&maxrecords=30&format=json&sort=datedesc`);return(data.articles||[]).slice(0,20).map(a=>({title:a.title||'Sem título',url:a.url,source:a.domain||a.sourcecountry||'Fonte externa',publishedAt:a.seendate?new Date(a.seendate).toISOString():new Date().toISOString(),sentiment:sentiment(`${a.title||''} ${a.snippet||''}`)}))}
function buildScore(technical,news,overall){const techParts={trend:technical.price>technical.sma20?100:0,longTrend:technical.price>technical.sma50?100:0,rsi:technical.rsi>=50&&technical.rsi<=70?100:technical.rsi>70?55:35,momentum:technical.macd>=0?100:35,volume:technical.volumeAboveAverage?100:45};const technicalScore=Math.round(average(Object.values(techParts)));const sentimentScore=Math.round((overall.score+100)/2);const newsScore=Math.round(Math.max(0,Math.min(100,50+average(news.map(n=>n.sentiment.score))*0.5)));const volumeScore=technical.volumeAboveAverage?85:45;const momentumScore=technical.macd>=0?85:35;const stabilityScore=Math.max(20,Math.min(100,100-technical.volatility*8));const score=Math.round(technicalScore*.30+sentimentScore*.20+newsScore*.20+volumeScore*.10+momentumScore*.10+stabilityScore*.10);const breakdown=[{key:'technical',label:'Técnica',value:technicalScore,weight:30,contribution:Math.round(technicalScore*.30)},{key:'sentiment',label:'Sentimento',value:sentimentScore,weight:20,contribution:Math.round(sentimentScore*.20)},{key:'news',label:'Notícias',value:newsScore,weight:20,contribution:Math.round(newsScore*.20)},{key:'volume',label:'Volume',value:volumeScore,weight:10,contribution:Math.round(volumeScore*.10)},{key:'momentum',label:'Momentum',value:momentumScore,weight:10,contribution:Math.round(momentumScore*.10)},{key:'stability',label:'Estabilidade',value:stabilityScore,weight:10,contribution:Math.round(stabilityScore*.10)}];const positives=[],negatives=[];if(technical.price>technical.sma20)positives.push('Preço acima da SMA20');else negatives.push('Preço abaixo da SMA20');if(technical.price>technical.sma50)positives.push('Preço acima da SMA50');else negatives.push('Preço abaixo da SMA50');if(technical.macd>=0)positives.push('Momentum técnico positivo');else negatives.push('MACD negativo');if(technical.volumeAboveAverage)positives.push('Volume acima da média');else negatives.push('Volume abaixo da média');if(overall.score>15)positives.push('Sentimento agregado positivo');if(overall.score<-15)negatives.push('Sentimento agregado negativo');if(technical.volatility>5)negatives.push('Volatilidade elevada');return{score,breakdown,positives,negatives,formula:'30% técnica + 20% sentimento + 20% notícias + 10% volume + 10% momentum + 10% estabilidade',version:'2.1'} }
async function generateAI(symbol,technical,news,score){const key=GEMINI_API_KEY.value();if(!key)return{summary:'IA não configurada. A pesquisa de notícias continua disponível.',risks:[],watch:[]};const compactNews=news.slice(0,12).map(n=>`${n.title} | ${n.source} | ${n.sentiment.label}`).join('\n');const prompt=`Você é um analista de pesquisa de mercado. Produza um relatório informativo, sem recomendar compra ou venda. Ativo: ${assetName(symbol)}. Score de pesquisa: ${score.score}/100. Dados técnicos: ${JSON.stringify(technical)}. Notícias recentes:\n${compactNews}\nResponda SOMENTE JSON válido no formato {"summary":"...","risks":["..."],"watch":["..."],"catalysts":["..."]}. Diferencie fatos de incertezas e não invente dados.`;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:0.2,responseMimeType:'application/json'}})});if(!r.ok)throw new Error(`Gemini HTTP ${r.status}`);const data=await r.json();const text=data.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'{}';try{return JSON.parse(text)}catch{return{summary:text,risks:[],watch:[],catalysts:[]}}}
async function buildResearch(symbol){const[ticker,klines,news]=await Promise.all([getJson(`${BINANCE}/ticker/24hr?symbol=${symbol}`),getJson(`${BINANCE}/klines?symbol=${symbol}&interval=1d&limit=60`),fetchNews(symbol)]);const closes=klines.map(x=>Number(x[4])),volumes=klines.map(x=>Number(x[5]));const price=Number(ticker.lastPrice),sma20=average(closes.slice(-20)),sma50=average(closes),r=rsi(closes),macd=ema(closes,12)-ema(closes,26),vol=volatility(closes.slice(-30)),volumeAverage=average(volumes.slice(-20));const technical={price,change24h:Number(ticker.priceChangePercent),volume24h:Number(ticker.volume),sma20,sma50,rsi:r,macd,volatility:vol,volumeAboveAverage:volumes.at(-1)>volumeAverage};const avg=news.length?Math.round(average(news.map(n=>n.sentiment.score))):0;const overall={score:avg,label:avg>15?'bull':avg<-15?'bear':'neutral'};const score=buildScore(technical,news,overall);const ai=await generateAI(symbol,technical,news,score);const now=new Date().toISOString();const result={symbol,asset:assetName(symbol),updatedAt:now,technical,sentiment:overall,score,news,ai};await db.collection('research').doc(symbol).set(result,{merge:true});await db.collection('research_history').add({...result,snapshotAt:now});return result}
function cors(req,res){res.set('Access-Control-Allow-Origin','*');res.set('Access-Control-Allow-Headers','Content-Type, Authorization');res.set('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS'){res.status(204).send('');return true}return false}
async function verifyUser(req){const header=req.headers.authorization||'';if(!header.startsWith('Bearer '))throw new Error('AUTH_REQUIRED');return admin.auth().verifyIdToken(header.slice(7))}
exports.api=onRequest({secrets:[GEMINI_API_KEY],timeoutSeconds:60},async(req,res)=>{if(cors(req,res))return;try{if(req.path==='/research'&&req.method==='GET'){const symbol=String(req.query.symbol||'BTCUSDT').toUpperCase();if(!SYMBOLS.includes(symbol))return res.status(400).json({error:'unsupported_symbol'});const cached=await db.collection('research').doc(symbol).get();if(cached.exists&&Date.now()-new Date(cached.data().updatedAt).getTime()<15*60*1000)return res.json(cached.data());return res.json(await buildResearch(symbol))}if(req.path==='/research/history'&&req.method==='GET'){const symbol=String(req.query.symbol||'BTCUSDT').toUpperCase();const limit=Math.min(Number(req.query.limit||30),100);let q=db.collection('research_history').where('symbol','==',symbol).orderBy('snapshotAt','desc').limit(limit);const snap=await q.get();return res.json({history:snap.docs.map(d=>({id:d.id,...d.data()}))})}if(req.path==='/alerts'&&req.method==='GET'){const user=await verifyUser(req);const snap=await db.collection('alerts').where('uid','==',user.uid).limit(50).get();return res.json({alerts:snap.docs.map(d=>({id:d.id,...d.data()})).filter(a=>a.active)})}if(req.path==='/alerts'&&req.method==='POST'){const user=await verifyUser(req);const{symbol,price,direction}=req.body||{};if(!SYMBOLS.includes(symbol)||!Number.isFinite(Number(price))||!['above','below'].includes(direction))return res.status(400).json({error:'invalid_alert'});const ref=await db.collection('alerts').add({uid:user.uid,symbol,price:Number(price),direction,active:true,triggered:false,createdAt:admin.firestore.FieldValue.serverTimestamp()});return res.status(201).json({id:ref.id})}return res.status(404).json({error:'not_found'})}catch(e){if(e.message==='AUTH_REQUIRED')return res.status(401).json({error:'auth_required'});console.error(e);return res.status(500).json({error:'server_error',message:e.message})}});
exports.researchScheduler=onSchedule({schedule:'every 15 minutes',timeZone:'America/Sao_Paulo',secrets:[GEMINI_API_KEY],timeoutSeconds:120},async()=>{for(const symbol of SYMBOLS){try{await buildResearch(symbol)}catch(e){console.error(`research ${symbol}`,e.message)}}});
exports.alertScheduler=onSchedule({schedule:'every 5 minutes',timeZone:'America/Sao_Paulo',timeoutSeconds:60},async()=>{const snap=await db.collection('alerts').where('active','==',true).limit(500).get();for(const doc of snap.docs){const a=doc.data();try{const ticker=await getJson(`${BINANCE}/ticker/price?symbol=${a.symbol}`);const current=Number(ticker.price);const hit=a.direction==='above'?current>=a.price:current<=a.price;if(hit)await doc.ref.update({active:false,triggered:true,triggeredAt:admin.firestore.FieldValue.serverTimestamp(),triggeredPrice:current})}catch(e){console.error(`alert ${doc.id}`,e.message)}}});